### ISSUE TITLE
Suggestions for Spatial Epigenome documentation

### ISSUE THREAD

**Issue by poorvi4** [atlasxomics/AtlasXpipeline_docs#1]
Hi @tamarajafar, thanks so much for the documentation edits! I have a few suggestions regarding the "Spatial Epigenome" documentation. @liyawang feel free to extend or remove to this list as you feel is necessary:

**Organization**

- Combine **Spatial Plots of Enriched Motifs** page with **Spatial Epigenome** page. Makes it easier to keep everything relating to the epigenome analysis all in one place. To differentiate between the various procedures in the analysis workflow include relevant titles for each section. For instance: Dependencies, Global variables/inputs, QC, ArchRProject Creation, Clustering, Adding Spatial Context, Peak Calling, Motif annotation, etc

**Content**
- For the content in **Spatial Plots of Enriched Motifs**, add brief descriptions as to why the following was done in each step of the analysis protocol. EX: We call peaks again after clustering on the original reads bc we can identify new peaks that might have been missed due to bulk calling procedures. Doesn't need to be too extensive. Should be a good mix between describing what we pass into the function and why we employ those methods.
- For the content in **FAQ**,  some questions should be centered around technical issues surrounding installation of particular packages and why certain parameters shouldn't be changed in our workflow since they're DBiT specific. Also, descriptions as to why we include certain dependencies and their role isn't necessarily needed esp if they only relate to plotting/graphics handling.
- For the **Glossary** section, we can probably skip definitions of each the parameters passed since this is defined in **Spatial Epigenome** and users don't necessarily need to use the same variable names they pass into each of the functions.

**Other**
- We can also skip the archR file containing the explanations of what clustering is and its different methods as this is something that users may already be familiar with or can look up in the archR/seurat tutorails we listed

I personally like ScanPy's documentation (Tutorials) which you can use as a reference/inspo: https://scanpy.readthedocs.io/en/stable/

**Comment by tamarajafar** [comment]
added these changes. thanks for your feedback.
